---
title: '2022-12-18 Gramps says "have fun"'
author: "Christian Coffman"
date: '2022-12-19'
tags:
- Story
- Fun
categories:
- Baby Stories
---


- One of the most important things my Gramps told me before games is "Have fun and don't start any fights".
- It was a cliche and I honestly didn't think much of it other than it being our little ritual before setting of to step on the ice
- Playing in high school when stakes were higher it was easy to be overwhelmed
  - Sometimes I would rise up to the occasion 
  - Sometimes it would get into my head and I would not enjoy the game making excuses
- When I lost site and made excuses that's when the game was no longer fun
- Now I realize that "have fun" wasn't a command from my grandpa, but rather a diagnostic tool for me to realize when something wasn't right
- The problem was that I wasn't really equiped at the time to recognize this and have the ability to kow that when it was no longer fun it was because something was off
- I now want you to have this knowledge 
- If you're not having fun you need to ask why?
  - I sit lkj???????