---
author: Christian
categories:
- Baby
date: "2022-12-18"
tags:
- Knowledge
- 
title: Prepping for baby 
---


My wife is currently 36 weeks pregnant with our baby girl. With her arrival just around the corner in the new year I want to make note of how we have been prepping for a our baby to arrive so that I will then be able to assess where we succeeded in preparation and where we could have done better.  

- Research
  - Reading is always a good first step to prepare for anything
  - For those utilitarians who don't alwasy see the point in reading 
    - Reading is distilling someone else's experiences for you to experience. In essence thsi saves you the time so that you don't need to make the same mistakes as them asnd can follow from their successes. This is the essence of the phrase "study history so that you aren't doomed to repeat it" - (Who said this?). "Some people don't learn from their mistakes. Smart people learn from their mistakes. Wise people learn from other people's mistakes" - (Who said this?)
- Prepping our home
- Prepping bodies and minds



